### ISSUE TITLE
Error running script on M2

### ISSUE THREAD

**Issue by lsherman98** [samuelbradshaw/text-to-timestamps#1]
Trying to use this script but it keeps erroring out. Would love to know if there is a solution. Error logs below. Thanks!

SOLVED: Was an SSL issue. Adding `import ssl
ssl._create_default_https_context = ssl._create_unverified_context` solved the issue

Starting…
2024-04-11 14:32:55.246096
torchvision is not available - cannot save figures
Checking for input data

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by samuelbradshaw** [comment]
Glad you were able to get it working!

**Comment by lsherman98** [comment]
Any suggestions on how to make it work for larger pieces of text? Right now
it shuts down if it's too long. Could just be the fact that I'm running
this on a MacBook Air.

**Comment by samuelbradshaw** [comment]
I think it's likely that the MacBook Air has something to do with it. The script does require a lot of resources and I haven't narrowed down the best combination yet to minimize load and time. Here are some things you could try:
- Test `whisperx` and `stable_ts` as the alignment_method, to see if one works better than the other.
- Try turning off use_voice_isolation, if you have it on.
- Try playing around with the parameters that are passed to `whisperx` and/or `stable_ts` (depending on which you're using) when the model is loaded. If you're using `whisperx`, the model is loaded on line 70 of text-to-vtt.py. If you're using `stable_ts`, the model is loaded on line 77 of text-to-vtt.py. You can see all of the available parameters [here](https://github.com/m-bain/whisperX/blob/main/whisperx/asr.py#L259) (whisperx) or [here](https://github.com/jianfch/stable-ts/blob/main/stable_whisper/whisper_word_level/original_whisper.py#L834) (stable_ts).

**Comment by lsherman98** [comment]
Awesome, thank you, ill play around with it.

**Comment by lsherman98** [comment]
Using `stable_ts` along with the `tiny.en` model is a world of a difference, results seem quite accurate so far.
